#!/bin/bash
echo "Enter number of rows:"
read n
for ((i=1;i<=n;i++))
do
for ((j=i;j<=n;j++))
do
echo -ne " "
done
for((j=1;j<=2*i-1;j++))
do
echo -ne "*"
done
echo
done


Enter number of rows:
6
      *
     ***
    *****
   *******
  *********
 ***********
